### ISSUE TITLE
CARACal INFO: exiting with error code 1

### ISSUE THREAD

**Issue by kmhess** [caracal-pipeline/caracal#1533] opened 2023-09-04 14:02 UTC
Hi,

I'm trying to run CARAcal on a slurm system that is *not* ilifu.  As far as I know it's "correctly" installed (although I did not do it).  Nonetheless, something is clearly wrong because I get the following error and I don't know what to do with it.  The `.stimela_workdir-16938348029524467` directory is present while caracal is running at some point, but then disappears by the time it crashes out with this error message.  I tried `export SINGULARITY_PULLFOLDER=/scratch/users/putyourusernamehere/STIMELA_IMAGES_NEW` recommendation from this issue, but it made no difference: https://github.com/caracal-pipeline/caracal/issues/1087

```
2023-09-04 15:45:20 CARACal.Stimela.summary_json-ms0-0 ERROR: cd /cephyr/NOBACKUP/groups/hess/antlia/hi/HI_2023/1_HI_caracal/1613847072/.stimela_workdir-16938348029524467 && singularity run --userns --workdir /cephyr/NOBACKUP/groups/hess/antlia/hi/HI_2023/1_HI_caracal/1613847072/.stimela_workdir-16938348029524467 --containall returns error code 1
2023-09-04 15:45:20 CARACal.Stimela.summary_json-ms0-0 ERROR: job failed at 2023-09-04 15:45:20.739173 after 0:00:28.085690
2023-09-04 15:45:21 CARACal ERROR: Job 'summary_json-ms0-0:: Get observation information as a json file ms=1613847072_sdp_l0_HI-cal.ms' failed: cd /cephyr/NOBACKUP/groups/hess/antlia/hi/HI_2023/1_HI_caracal/1613847072/.stimela_workdir-16938348029524467 && singularity run --userns --workdir /cephyr/NOBACKUP/groups/hess/antlia/hi/HI_2023/1_HI_caracal/1613847072/.stimela_workdir-16938348029524467 --containall returns error code 1 [PipelineException]
2023-09-04 15:45:21 CARACal INFO:   More information can be found in the logfile at output_1613847072/logs-20230904-153954/log-caracal.txt
2023-09-04 15:45:21 CARACal INFO: exiting with error code 1
```

Thanks in advance for your help.

**Comment by KshitijT** [comment] 2023-09-04 18:04
@kmhess, could you please share the log and the config file ?

**Comment by paoloserra** [comment] 2023-09-05 07:45
Have you tried with CARACal's latest stable release?

**Comment by pharaofranz** [comment] 2023-09-05 07:48
That's v1.0.7, is it? -- not yet.

**Comment by pharaofranz** [comment] 2023-09-05 07:50
It's actually not entirely clear to me which version we're running. pip tells me it's 1.1.1, `caracal --version` tells me it's 1.0.6 as also seen in the logs.

**Comment by paoloserra** [comment] 2023-09-05 07:52
mmmm... I let others comment on this, I'm not the best in the team with software versions, pip, etc etc (as the above error shows)

**Comment by pharaofranz** [comment] 2023-09-05 08:43
No joy with v1.0.7 -- exactly the same issue.
[logs-20230905-103639.txt](https://github.com/caracal-pipeline/caracal/files/12521061/logs-20230905-103639.txt)
[logs-20230905-103933.txt](https://github.com/caracal-pipeline/caracal/files/12521062/logs-20230905-103933.txt)
[logs-20230905-104124.txt](https://github.com/caracal-pipeline/caracal/files/12521063/logs-20230905-104124.txt)

**Comment by paoloserra** [comment] 2023-09-05 09:13
Which Stimela version are you running? I would suggest to make one last try with Stimela 1.7.6, which is the stable release I use succesfully with Caracal 1.0.7.

Sorry for the pain ...

**Comment by pharaofranz** [comment] 2023-09-05 09:23
I was running 1.7.8, downgraded to 1.7.6. No joy :-( Same issue.

**Comment by pharaofranz** [comment] 2023-09-05 09:41
Is it possible to get more info from the singularity images than just 'finished with exit code 1'? The temporary work directory `./stimela_workdir-<random_number_string>` disappears right after the pipeline ran such that one cannot re-run the command that threw the error by oneself. Using the `--debug` flag didn't really help much either yet.

**Comment by pharaofranz** [comment] 2023-09-05 15:05
I now reverse-engineered what caracal is doing in terms of running singularity images.

I now ran caracal again with `-debug` enabled as I realized that one gets to see the actual singularity command that is run. Once the script drops into `pdb`, I copy/rsync the content of `.stimela_workdir-<random-number>` somewhere else before exiting pdb. I then copy that directory back to where it was before with the same name as before. I then define a bunch of environment variables that are being reported as set (e.g. `export SINGULARITYENV_STIMELA_MOUNT=/stimela_mount; export SINGULARITYENV_OUTPUT=${SINGULARITYENV_STIMELA_MOUNT}/output` and so on). Then I rerun the singularity command as I see it from the pipeline, i.e.

`cd /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/.stimela_workdir-16939197495247493 && singularity run --workdir /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/.stimela_workdir-16939197495247493 --containall  --bind /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/.stimela_workdir-16939197495247493/stimela_parameter_files/elevation_plots_ms0-2304369160654416939197497773852.json:/stimela_mount/configfile:ro --bind /cephyr/NOBACKUP/groups/hess/franz/software/caracal-1.0.7/lib/python3.9/site-packages/stimela/cargo/cab/owlcat_plotelev/src:/stimela_mount/code:ro --bind /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/.stimela_workdir-16939197495247493/passwd:/etc/passwd:rw --bind /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/.stimela_workdir-16939197495247493/group:/etc/group:rw --bind /cephyr/NOBACKUP/groups/hess/franz/software/caracal-1.0.7/bin/stimela_runscript:/singularity:ro --bind /cephyr/NOBACKUP/groups/hess/antlia/hi/HI_2023/0_HI_raw:/stimela_mount/msdir:rw --bind /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/input:/stimela_mount/input:ro --bind /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/msdir:/stimela_mount/output:rw --bind /cephyr/NOBACKUP/groups/hess/franz/caracal-tests/HI_2023_1_HI_caracal_1613847072/msdir/tmp:/stimela_mount/output/tmp:rw /cephyr/NOBACKUP/groups/hess/franz/software/caracal-images2/stimela_owlcat_1.6.6.img /singularity`

As expected, this finishes without errors and I get a nice new elevation plot.

IMHO this has nothing to do with singularity or apptainer. But I have a hard time figuring out where else to look now. I am attaching the latest log that I have with `[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/12525157/log-caracal.txt)` enabled.

**Comment by paoloserra** [comment] 2023-09-06 08:31
@SpheMakh I think we need your input here

**Comment by pharaofranz** [comment] 2023-09-06 14:33
Haha, fun fact: it would appear somebody updated stimela to version 1.7.9 since yesterday. This comes with a bunch of new singularity images. That only coincided with my system-python test leading me to false conclusions as the system-python build of caracal pulled stimela 1.7.9... Everything works fine with stimela_1.7.9 -- both the system-python and the module-load-python.

**Comment by paoloserra** [comment] 2023-09-07 06:40
OK @pharaofranz , many thanks for the detailed reporting. Maybe one of the Stimela folks could comment on this before we close the issue?

**Comment by Athanaseus** [comment] 2023-09-07 07:29
Hi @pharaofranz, thank you for the issue.
I can confirm that the latest `stimela-classic` version 1.7.9 added support for apptainer/singularity.
I will also attempt to reproduce this error to see why it occurred.
@francescaLoi may have reported a related issue due to a different environment setup.
I'm preparing a pre-release of `caracal` with the latest updates, and any apptainer-related issues can be tested against this.

**Comment by Athanaseus** [comment] 2024-06-11 09:47
Please re-open if experiencing the issue.

**Closed by Athanaseus** 2024-06-11 09:47 UTC
