### ISSUE TITLE
Cleaning stuck with multiscale 

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#840] opened 2020-03-17 10:59 UTC
Hello,

In MeerKATHI I am using the multi_scale option with multi_scale_scales. I only used 3 scales 10,25,50, but the wsclean stuck at a particular position and not progressing further. Any thoughts? The problem is the same with using mask also.  

....
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447
Iteration 16017, scale 10 px : -1.32 mJy at 3766,2447

Thanks

Cheers, Viral

**Comment by o-smirnov** [comment] 2020-05-17 20:01
OK this is a duplicate of #1110, so I'll close it again.

**Closed by o-smirnov** 2020-05-17 20:01 UTC
