### ISSUE TITLE
Discrepancy in paraller deconvolution number

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1248] opened 2020-10-01 12:24 UTC
I found discrepancy in paraller deconvolution number supply to the caracal config file and output image header parameter. I set `img_nrdeconvsubimg: 1024` in the selfcal worker, but in output image header it says `-parallel-deconvolution 188`. Why these two numbers are different?

**Comment by o-smirnov** [comment] 2020-10-01 13:14
The former specifies the number of sub-images, the latter is the max size of the sub-image in pixels, so they're in a sense reciprocal. Not sure why we made the caracal parameter the reciprocal, but there you have it.

Also not sure if 1024 actually means sqrt(1024) x sqrt(1024) sub-images (@KshitijT?), but either way it seems too high to me -- no point having more sub-images than CPU cores...

**Comment by paoloserra** [comment] 2020-10-01 14:33
Indeed, CARACal asks the user to set the number of sub-images. Back then we thought this would be more easily linked to the nr of CPUs one wishes to use. Nobody objected, so that's what we did. :)

**Comment by paoloserra** [comment] 2020-10-01 14:35
BTW, see https://caracal.readthedocs.io/en/latest/manual/workers/selfcal/index.html#img-nrdeconvsubimg

**Comment by KshitijT** [comment] 2020-10-01 15:04
The relevant code in the worker is:

```
    nrdeconvsubimg = ncpu if config['img_nrdeconvsubimg'] == 0 else config['img_nrdeconvsubimg']
    if nrdeconvsubimg == 1:
        wscl_parallel_deconv = None
    else:
        wscl_parallel_deconv = int(np.ceil(config['img_npix']/np.sqrt(nrdeconvsubimg)))
```

So in @viralp 's case, where img_nrdeconvsubimg is set to 1024, it is taken as the number of _total_ subimages - so npix/sqrt(1024) would be the max 1-D size of the subimages; so if you have npix set to ~ 6000, we see what's expected and then this is not a bug.

>  no point having more sub-images than CPU cores

True, maybe we should have a fallback mechanism if such is the case. In this case I think 32 is just fine? Following wsclean wiki advice, I generally aim for ~1000 pixels as the max size for subimages.

**Comment by KshitijT** [comment] 2020-10-01 16:14
Closing the issue, after chatting with @viralp (private communication).

**Closed by KshitijT** 2020-10-01 16:14 UTC

**Comment by paoloserra** [comment] 2020-10-01 16:41
> I generally aim for ~1000 pixels as the max size for subimages.

Which is indeed the WSclean recommended minimum size, too. We could update our docs to give this advice.
