### ISSUE TITLE
proposal for specifying non-default Stimela image versions

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1124] opened 2020-05-19 11:00 UTC
So, we'd like to be able to run different (non-default) versions of (some) Stimela images in the pipeline. I propose the following.

* At the moment, a given Stimela release specifies a specific tag for every image. This is the "default" set of tags, and this is what we run with. Any new Stimela release will have a new set of default tags (baked into the parmeter.json file of each cab).

* But, we need to give the user the capacity to run non-default images.

* The config file shall have an optional ``general: cabs`` section, in which non-default tags can be specified:

  ```
  general:
    cabs:
      wsclean: X.Y.Z-foo
  ```
  This tells the pipeline to use tag X.Y.Z-foo for the wsclean image, instead of the default image, wherever wsclean is used in the pipeline. Anything not mentioned in this section just uses the normal default release tag.

* However, we also want to be able to override this at the worker level, if needed. So a worker should also recognize a ``cabs`` section, which would force that specific worker use a non-default image tag:

  ```
  selfcal:
    cabs:
      wsclean: X.Y.Z-foo
  ```
  The general cabs setting override the defaults, and the per-worker cabs override that on top. **So different workers could potentially even use different software versions.**

There are various use cases for this:

* We could quickly deploy hotfixes for things like #1109 and #1110, just by uploading a new image for e.g. cubical, and telling the users to adjust their tag.

* Likewise, during bughunting/bugfixing it would be easy to quickly try a different/experimental version of a package, to see if that solves a particular problem.

* it would provide a more elegant way of using "vintage" versions such as e.g. CASA 4.7 for polcal.

Regarding the latter point, I would actually extend the proposal with the following:

  ```
  polcal:
    cabs:
      casa_foo: casa_47_foo
  ```

or

  ```
  polcal:
    cabs:
      casa_foo: casa_47_foo:X.Y.Z
  ```

That is, if two "parallel" image versions are maintained long-term (such as modern CASA and CASA 4.7), it might be more sensible to still reflect this in the image name and not the tag (as is done in Stimela now, actually. @SpheMakh has releases of the CASA cabs, and the CASA 4.7 cabs.) The setting above then acts as an alias, it tells Stimela to use a differently named image (but can also specify a particular tag of that image).

**Comment by o-smirnov** [comment] 2020-05-19 11:00
Discuss please. I think this is pretty simple and logical.

**Comment by gigjozsa** [comment] 2020-05-19 11:40
With even tags of an image the situation gets quite complicated, so I would regard this as a higher-Dan operation.

**Comment by KshitijT** [comment] 2020-05-19 11:43
> With even tags of an image the situation gets quite complicated, so I would regard this as a higher-Dan operation.

That particular option can be for developers only and can be hidden from general usage. Otherwise, this is pretty similar to what we had for crosscal worker with the `casa_version` option and that was working fine and not the cause of too much confusion.

**Comment by o-smirnov** [comment] 2020-05-19 11:45
Well it's definitely a bring-out-the-rope moment. But as @Kshitij points out, it's just generalizing the ``casa_version`` situation. We might be needing something similar for wsclean, at least for a while. And one single unified mechanism causes less confusion, IMHO.

**Comment by gigjozsa** [comment] 2020-05-19 11:46
No, the concept is a very good suggestion, but the tagging thing should be hidden from the general user.

**Comment by svw26** [comment] 2020-05-19 11:56
In the user's eyes, it'll be just another number that they don't really need to worry about. But if it helps the communication between user and developer, I don't see why the tag number can't be visible to everyone. x

**Comment by gigjozsa** [comment] 2020-05-19 11:58
What I mean is that we should implement the tag number as another layer of manual specification. There should be a default without tag number.

**Comment by KshitijT** [comment] 2020-05-19 12:01
> What I mean is that we should implement the tag number as another layer of manual specification. There should be a default without tag number.

Well, there'll be a schema option for that (default would be whatever is standard), I guess. I just meant that it does not need to go in any of the config files explicitely.

**Comment by gigjozsa** [comment] 2020-05-19 12:05
What I mean both should be possible:
```
  polcal:
    cabs:
      casa_foo: casa_47_foo
  ```

or

  ```
  polcal:
    cabs:
      casa_foo: casa_47_foo:X.Y.Z
  ```

**Comment by o-smirnov** [comment] 2020-05-19 12:08
Yes both should be possible. Exactly what I meant. And if there's nothing
specified, then the default release versions are used.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by PeterKamphuis** [comment] 2020-05-19 13:01
Mostly makes sense to me but if we set cab tags in the schemas we should makes sure they get removed as soon as an issue is resolved in the software. 

We can complain about #1109  but if that Cubical version had not gone into CARACal we might still  not have known about the bug. So we should ensure somehow that this remains a uniform way to quickly roll back software versions when a bug is identified, not a way to fix software versions.

**Comment by o-smirnov** [comment] 2020-05-19 13:37
> Mostly makes sense to me but if we set cab tags in the schemas we should makes sure they get removed as soon as an issue is resolved in the software.

It had not occurred to me to set cab tags in the schemas, and I don't think it would be a good idea at all. Too easy to bury and forget them there.

I rather envision a "default" set of tags that means whatever the installed Stimela release thinks is the default, and config files that can override this default with specific tags, in the interest of temporary bug fixes or testing.

This is also why I prefer the 4.7 part of CASA 4.7 to be the image name, not a tag. It's a "big compatibility issue" kind of thing, not a "quick bugfix" thing. Possibly the same goes for wsclean, so perhaps  ``wsclean_26`` makes sense, if we anticipate having that version hang around for a bit.

**Comment by PeterKamphuis** [comment] 2020-05-19 14:07
> It had not occurred to me to set cab tags in the schemas, and I don't think it would be a good idea at all. Too easy to bury and forget them there.
>

 I understood it to be @KshitijT  suggestion but I agree (and worried) that they could become frozen there far too easily.

**Comment by paoloserra** [comment] 2020-05-20 15:41
I like the idea. I also agree that this could be set at `general` and overwritten by each worker.

However, because of my limited understanding of Stimela I am a little confused about a few things:

- Different cabs have different tags in the same Stimela release. E.g., in Stimela 1.5.4, `wsclean` has tag 1.2.3 (even though the parameters.json file seems to have been edited after Stimela 1.2.3) while `autoflagger` has  tag 1.2.0 (also in this case the parameters.json file was edited after Stimela 1.2.0). How we're going to set the default tag to whatever is in the installed Stimela release? The highest available tag?
- All pipeline parameters must go in the schema and these new parameters are no exception. I guess the proposal is to have something like `<worker>: cabs: ''` in the schema of each worker, so all cabs in that worker get the default/higher tag?
- How we're going to use a different image of a worker (i.e., a different tag) if that image lives in a different Stimela release? Or are you saying that from now on each Stimela release will come with multiple images of a same task, each with its own tag? That's not the current behaviour, right? Will this blow up the total size of Stimela's Singularity images?

**Comment by o-smirnov** [comment] 2020-05-20 15:54
> Different cabs have different tags in the same Stimela release

Yes, a tag is purely a per-cab property. The set of tags associated with different cabs have no defined relationship to each other.

> How we're going to set the default tag to whatever is in the installed Stimela release?

We don't need to worry about that. Any specific Stimela release has its "default" set of tags (whatever is in the parameters.json of each cab). Caracal's default is "nothing", which means defer to the Stimela default.

> All pipeline parameters must go in the schema and these new parameters are no exception.

The schema should specify nothing more than a default of "nothing" for the cabs subsection. 

> How we're going to use a different image of a worker (i.e., a different tag) if that image lives in a different Stimela release?

Images live on the docker hub (and/or as copies in the shared directory we provide). The hub is just a big bag of images, with any number of tags. When a new release is made, new versions are thrown into the bag, but the old ones are still there. An old image, or a new experimental image, can be fetched just by specifying a tag (modulo ILIFU network quirks.)

**Comment by paoloserra** [comment] 2020-05-20 15:56
OK thanks.

**Comment by paoloserra** [comment] 2020-05-21 07:21
Another thought I've had is what happens when two images have different options. E.g. WSclean 2.8 may  have extra options compared to 2.6. We need CARACal to know when an option included in the schema can be used. Or am I thinking about it the wrong way?

**Comment by o-smirnov** [comment] 2020-05-21 09:04
Well, there's only so many ways to skin a cat before it dies... let us be sensible about it...

To first order, let's ignore the problem. Swapping cab versions around is own-risk, twisted rope activity, so if there's an interface mismatch and the pipeline crashes ingloriously, so be it.

For hotfixes this should not be a problem.

In the (very few) cases where we maintain "vintage" cabs going forward (CASA 4.7, wsclean 2.6 perhaps), @SpheMakh can do something intelligent in the older cab. Perhaps ignore the extra parameters, and print a warning.

**Comment by paoloserra** [comment] 2020-05-21 09:06
OK, so this cannot be handled by the worker itself? E.g., do not pass a certain option if the tag is not such and such?

**Comment by o-smirnov** [comment] 2020-05-21 09:10
I would be very hesitant to start putting such monkey-patchey logic into the worker.

Rather, the 2.6 cab run.py script can say "hang on, I have a 2.8 option here, let's do something intelligent".

Anyway it should only be needed in that one exceptional case, if at all. In general, I say we just plug the image in, and if it explodes into the user's face, fine.

**Comment by paoloserra** [comment] 2020-05-21 09:17
Ok, we'll see

**Closed** 2020-05-26 09:16 UTC
Labels: enhancement
