### ISSUE TITLE
Corrupt container?

### ISSUE THREAD

**Issue by AlecThomson** [caracal-pipeline/caracal#1432] opened 2022-07-10 03:23 UTC
This may an upstream issue in [stimela](https://github.com/ratt-ru/Stimela), but I'm getting this same error repeatedly. I've tried purging the and rebuilding the Stimela containers (including the cache). But it seems like the ragavi container is corrupt. 

Are there any other steps I should take to try to get around this?

Thanks!

Relevant error message:
```
# FATAL:   could not open image /scratch2/tho822/singularity_images/stimela_ragavi_1.7.3.sif: SIF image /scratch2/tho822/singularity_images/stimela_ragavi_1.7.3.sif is corrupted: wrong partition size
2022-07-09 21:11:45 CARACal.Stimela.plotgains-K-0-0 ERROR: cd /scratch2/tho822/MeerKAT/caracal_test/.stimela_workdir-16573647804728236 && singularity run --workdir /scratch2/tho822/MeerKAT/caracal_test/.stimela_workdir-16573647804728236 --containall returns error code 255
2022-07-09 21:11:45 CARACal.Stimela.plotgains-K-0-0 ERROR: job failed at 2022-07-09 21:11:45.028982 after 0:00:00.051462
2022-07-09 21:11:45 CARACal ERROR: Job 'plotgains-K-0-0:: Plot gaincal phase' failed: cd /scratch2/tho822/MeerKAT/caracal_test/.stimela_workdir-16573647804728236 && singularity run --workdir /scratch2/tho822/MeerKAT/caracal_test/.stimela_workdir-16573647804728236 --containall returns error code 255 [PipelineException]
```
[Full log and config](https://gist.github.com/AlecThomson/b0a6ea2242d96634a391b9cb3608c719)

**Comment by o-smirnov** [comment] 2022-07-27 08:46
Hmm odd, never seen that error. "Corrupted: wrong partition size"?? @SpheMakh any comments?

Maybe @Athanaseus should try rolling a 1.7.4 ragavi image in stimela to see if this goes away.

**Comment by Athanaseus** [comment] 2022-07-27 09:46
I can't reproduce this. Before building `1.7.4` (which has no changes) can you run the following recipe using `stimela`.


`mkdir test`
`cd test/`
`mkdir output input msdir`
`cp /path/to/gain/table/mypipelinerun-1603319074-1kgb_primary.K0 output/`
`vi ragavi_cab.py`

```
import stimela

INPUT = "input"
OUTPUT = "output"
MSDIR = "msdir"
PREFIX = "test"

recipe = stimela.Recipe("Stimela ragavi example", ms_dir=MSDIR,
                                       JOB_TYPE="singularity" )

table = "mypipelinerun-1603319074-1kgb_primary.K0"

recipe.add("cab/ragavi", "gain_plotter",
           {
                "table"   :   f"{table}:output",
                "htmlname":   f"{PREFIX}-K"
           },
           input=INPUT,
           output=OUTPUT,
           label="ragavi::ragavi")

recipe.run()
``` 

`(stimela) $ python ragavi_cab.py`

**Comment by AlecThomson** [comment] 2022-07-28 07:28
Thanks @o-smirnov  and @Athanaseus!

Some quick updates - I was able to 'workaround' this issue by manually running singularity pull outside of Stimela. All seemed to run fine after that.

Here is the result of running the above script:
```
test> python ragavi_cab.py
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: ---------------------------------
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: Stimela version 1.7.5
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: Running: Stimela ragavi example
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: ---------------------------------
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: Config directory cannot be found. Will create /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146/stimela_parameter_files
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: Adding cab '/scratch2/tho822/singularity_images/stimela_ragavi_1.7.3.sif' (x.x.x) to recipe, container name 'gain_plotter'
2022-07-28 17:23:52 STIMELA.gain_plotter INFO: job started at 2022-07-28 17:23:52.516022
2022-07-28 17:23:52 STIMELA.Stimela ragavi example INFO: STEP 1 :: ragavi::ragavi
2022-07-28 17:23:52 STIMELA INFO: Validating parameters for cab ragavi (stimela/ragavi:1.7.3)
2022-07-28 17:23:52 STIMELA INFO: Location of 'table' was specified as 'output'. Will overide default.
2022-07-28 17:23:52 STIMELA INFO: Parameters validated and saved to /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146/stimela_parameter_files/gain_plotter-2345623020388816589930324947977.json
2022-07-28 17:23:52 STIMELA.gain_plotter INFO: Starting container [gain_plotter-2345623020388816589930324947977]. Timeout set to -1. The container ID is printed below.
# running cd /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146 && singularity run --workdir /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146 --containall  --bind /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146/stimela_parameter_files/gain_plotter-2345623020388816589930324947977.json:/stimela_mount/configfile:ro --bind /scratch2/tho822/miniconda3/envs/caracal/lib/python3.10/site-packages/stimela/cargo/cab/ragavi/src:/stimela_mount/code:ro --bind /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146/passwd:/etc/passwd:rw --bind /scratch2/tho822/MeerKAT/caracal_test/test/.stimela_workdir-16589930324855146/group:/etc/group:rw --bind /scratch2/tho822/miniconda3/envs/caracal/bin/stimela_runscript:/singularity:ro --bind /scratch2/tho822/MeerKAT/caracal_test/test/msdir:/stimela_mount/msdir:rw --bind /scratch2/tho822/MeerKAT/caracal_test/test/input:/stimela_mount/input:ro --bind /scratch2/tho822/MeerKAT/caracal_test/test/output:/stimela_mount/output:rw --bind /scratch2/tho822/MeerKAT/caracal_test/test/output/tmp:/stimela_mount/output/tmp:rw /scratch2/tho822/singularity_images/stimela_ragavi_1.7.3.sif /singularity
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
# 2022-07-28 17:23:56: Initial memory state:
# 2022-07-28 17:23:56:               total        used        free      shared  buff/cache   available
# 2022-07-28 17:23:56: Mem:           503G         71G        232G        4.4G        198G        423G
# 2022-07-28 17:23:56: Swap:           31G         59M         31G
# 2022-07-28 17:23:56: Running ragavi-gains --table /stimela_mount/output/mypipelinerun-1603319074-1kgb_primary.K0 --cmap coolwarm --htmlname /stimela_mount/output/test-K
# 28.07.2022@17:24:01 - ragavi.ragavi        - INFO       - Table type: K Jones
# 28.07.2022@17:24:01 - ragavi.ragavi        - INFO       - Spw: 0, Field: J0408-6545, Corr: 0 delay
# 28.07.2022@17:24:01 - ragavi.ragavi        - INFO       - Table type: K Jones
# 28.07.2022@17:24:05 - ragavi.ragavi        - INFO       - Spw: 0, Field: J0408-6545, Corr: 1 delay
# 28.07.2022@17:24:05 - ragavi.ragavi        - INFO       - Table type: K Jones
# 28.07.2022@17:24:09 - ragavi.ragavi        - INFO       - Table /stimela_mount/output/mypipelinerun-1603319074-1kgb_primary.K0 done.
# 28.07.2022@17:24:10 - ragavi.ragavi        - INFO       - Rendered HTML: /stimela_mount/output/test-K.html
2022-07-28 17:24:10 STIMELA.gain_plotter INFO: job complete at 2022-07-28 17:24:10.851479 after 0:00:18.335457
2022-07-28 17:24:10 STIMELA.Stimela ragavi example INFO: Saving pipeline information in .last_Stimela_ragavi_example.json
2022-07-28 17:24:10 STIMELA.Stimela ragavi example INFO: Recipe executed successfully
```
One particular pain is that my python envs were recenly zapped by a disk purge on my HPC, so this from a new build of caracal etc. - which makes reproduction hard, I'm sorry :/ Please let me know, though, if there are any further tests I could run on my end.

**Comment by Athanaseus** [comment] 2022-08-01 13:53
@AlecThomson glad it works for you, this should be good.
I'll close this, and feel free to open it if you experience a similar issue.

**Closed by Athanaseus** 2022-08-01 13:53 UTC
